.TH mconnect 1
.SH NAME
mconnect \- connect to the SMTP server on a host
.SH SYNTAX
.B mconnect
[
.I host
[
.I port
]
]
.SH DESCRIPTION
.B mconnect
connects to
.I port
on
.IR host .
It sends its input to
.IR host ,
adding a CR to each line.
Meanwhile it prints anything it receives from
.IR host .

If
.I port
is not supplied,
.B mconnect
uses port 25 (SMTP).

If
.I host
is not supplied,
.B mconnect
connects to the local host.
.SH "SEE ALSO"
tcpclient(1)
